### ISSUE TITLE
What are the units of d2, d3, d4?

### ISSUE THREAD

**Issue by DanHickstein** [omelchert/pyGLLE#2]
Sorry about this basic question, I am new to the LLE. But what are the units of d2, d3, and d4? Are they related to the beta expansion coefficients, in units of ps^2/km or similar?

**Comment by omelchert** [comment]
Hey Dan,

Thank you for your interest :) When working with the LLE/GLLE I was so fortunate to work on fundamental properties of cavity solitons and their dynamical evolution. I did not have to deal with expansion coefficients in real-world units, and, thus, in the given context, the expansion coefficients d2, d3, and d4 are simply dimensionless (as is the whole equation). 

If you are interested in working with the dimensionless GLLE, Ref. [Xu, Coen; Opt. Lett. 39, 3492 (2014)](https://doi.org/10.1364/OL.39.003492) points out how d3 is related to beta2 and beta3.

Instead, if you would like to model the LLE/GLLE in real-world units, a description of the LLE/GLLE in terms of the actual field and the expansion coefficients beta is detailed in Ref. [Coen et al.; Opt. Lett. 38, 37 (2013)](https://doi.org/10.1364/OL.38.000037).

Best wishes
Oliver

PS: In order to perform tests and for redundancy, I use - besides the high-order Runge-Kutta method provided here - a split-step Fourier method. Therefore I implemented a solver class along with the different types of solvers. If you are interested to build upon them, I will update this repository accordingly ... but I will need some time to arrange for this (on the scale of 1-2 weeks, I guess).

**Comment by DanHickstein** [comment]
Thanks for the references! I didn't finish figuring this out yet (got distracted and stated using PyLLE in the mean time), but hopefully I will be able to circle back to this eventually. I'll close this issue, as I think you've answered the main question here. (Answer is that they are unitless.)
